query vehicle($id: String!) {
  vehicle(id: $id) {
    id
    vehicleDetails {
      id
      make
      model
      year
      image {
        label
        hero {
          md
        }
      }
    }
  }
}
